### PR TITLE
Add media event and request

### PR DESCRIPTION
**Pull request by 715209**
Adds the Media events, Media Control requests and also GetMediaSourcesList.
Hope you haven't already done this in #3 :smile:

### CODE REVIEW

**Comment by dnaka91** [comment]
Hey @715209 thanks for the great work.

Unfortunately I already have these changes locally as I'm preparing the upgrade to `4.9.0` and my changes match almost 100% with yours 😅. 

There are a few other changes to the existing APIs and tons of new integration tests to prepare so it will take me a few more days to push that.

**Comment by 715209** [comment]
Ah I probably should have asked how far you were :stuck_out_tongue:
Thanks for creating this awesome library though!

**Comment by dnaka91** [comment]
Thanks for taking it lightly. That was sure a lot of work to put all the changes together.
I'm really sorry that I had to refuse your PR. 

Should have pushed my local changes early and make a preview PR so people see that I'm building something already.
Anyways, thanks for the effort and for understanding 🙇

**Comment by 715209** [comment]
Don't worry about it! I had fun going through your code and learning some rust stuff.

**Pull request closed without merging**
